/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhoso;

import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author andre
 */
public class TelaJogo extends javax.swing.JFrame {

    private ControladorJogo controlador;
    private Container conteudos;
    private JButton[][] quadrados = new JButton[ControladorJogo.MAX_POSICOES][ControladorJogo.MAX_POSICOES];
    private ImageIcon imagemInimigo = new ImageIcon("inimig.png");
    
    //Init componentes:
    public TelaJogo () {
        super("Clique nos inimigos para ganhar!");
        
        this.conteudos = this.getContentPane();
        this.conteudos.setLayout(new GridLayout(ControladorJogo.MAX_POSICOES,ControladorJogo.MAX_POSICOES));
        
        TratadorDeBotoes tratadorDeBotao = new TratadorDeBotoes();
        
        for (int i = 0; i < ControladorJogo.MAX_POSICOES; i++) {
            for (int j = 0; j < ControladorJogo.MAX_POSICOES; j++) {
                this.quadrados[i][j] = new JButton();
                this.quadrados[i][j].addActionListener(tratadorDeBotao);
                this.conteudos.add(this.quadrados[i][j]);
                
            }
        }
        
        //Chamar metodo para atualizar os inimigos aqui
        
        this.setSize(800,800);
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        setVisible(true);
        
    }
    
    private class TratadorDeBotoes implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            JButton botaoClicado = (JButton) e.getSource();
            
            for (int i = 0; i < ControladorJogo.MAX_POSICOES; i++) {
                for (int j = 0; j < ControladorJogo.MAX_POSICOES; j++) {
                    if (botaoClicado.equals(TelaJogo.this.quadrados[i][j])) {
                        //Executa comando passando i e j
                        System.out.println("Posição X=" + i + " e Y=" + j);
                        return;
                    }
                }
            }
            
        }
        
    }
    
    /**
     * Creates new form TelaJogo
     */
    //public TelaJogo() {
    //    initComponents();
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
